name: Daily Amplitude Charts to Slack

on:
  schedule:
    # 매일 오전 9시에 실행 (UTC 기준, 한국 시간으로는 UTC+9)
    # 한국 시간 오전 9시 = UTC 0시
    - cron: '0 0 * * *'
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  send-amplitude-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Send Amplitude charts to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python scripts/send_amplitude_charts.py
